export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const CHANGE_TASK_TITLE = 'CHANGE_TASK_TITLE';
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const CHANGE_TASK_DESCRIPTION = 'CHANGE_TASK_DESCRIPTION';
export const CHANGE_TASK_PRIORITY = 'CHANGE_TASK_PRIORITY';

export const ADD_SUBTASK = 'ADD_SUBTASK';
export const CHANGE_SUBTASK_STATUS = 'CHANGE_SUBTASK_STATUS';
export const CHANGE_SUBTASK_TITLE = 'CHANGE_SUBTASK_TITLE';
export const REMOVE_SUBTASK = 'REMOVE_SUBTASK';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_REPLY_COMMENT = 'ADD_REPLY_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const ADD_FILE = 'ADD_FILE';
export const REMOVE_FILE = 'REMOVE_FILE';
